name: 📢 Add Temple Notification
description: Add a new notification for the website
title: "[NOTIFICATION] "
labels:
  - notification
body:
  - type: input
    id: title
    attributes:
      label: Notification Title
      placeholder: e.g. Darshan Update
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Notification Content
      placeholder: e.g. Temple will open after 12 PM today.
    validations:
      required: true

  - type: input
    id: timestamp
    attributes:
      label: Date
      placeholder: e.g. 14-Feb-26
    validations:
      required: true
