name: 📢 Add Temple Notification
description: Create a notification that will be published on the website
title: "notification"

body:
  - type: input
    id: notif_title
    attributes:
      label: Notification Title
      description: Short heading for the notification
      placeholder: e.g. Darshan Update
    validations:
      required: true

  - type: textarea
    id: notif_content
    attributes:
      label: Notification Content
      description: Full notification message
      placeholder: e.g. Temple will open after 12 PM today.
    validations:
      required: true

  - type: input
    id: notif_date
    attributes:
      label: Date
      description: Date to be shown on the website
      placeholder: e.g. 14-Feb-26
    validations:
      required: true
